/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as ThemesZustandRouteImport } from './routes/themes/zustand'
import { Route as ThemesReduxRouteImport } from './routes/themes/redux'
import { Route as ThemesContextRouteImport } from './routes/themes/context'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any)
const ThemesZustandRoute = ThemesZustandRouteImport.update({
  id: '/themes/zustand',
  path: '/themes/zustand',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesReduxRoute = ThemesReduxRouteImport.update({
  id: '/themes/redux',
  path: '/themes/redux',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesContextRoute = ThemesContextRouteImport.update({
  id: '/themes/context',
  path: '/themes/context',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forms': typeof FormsRoute
  '/posts': typeof PostsRouteWithChildren
  '/search': typeof SearchRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/themes/context': typeof ThemesContextRoute
  '/themes/redux': typeof ThemesReduxRoute
  '/themes/zustand': typeof ThemesZustandRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forms': typeof FormsRoute
  '/search': typeof SearchRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/themes/context': typeof ThemesContextRoute
  '/themes/redux': typeof ThemesReduxRoute
  '/themes/zustand': typeof ThemesZustandRoute
  '/posts': typeof PostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forms': typeof FormsRoute
  '/posts': typeof PostsRouteWithChildren
  '/search': typeof SearchRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/themes/context': typeof ThemesContextRoute
  '/themes/redux': typeof ThemesReduxRoute
  '/themes/zustand': typeof ThemesZustandRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forms'
    | '/posts'
    | '/search'
    | '/posts/$postId'
    | '/themes/context'
    | '/themes/redux'
    | '/themes/zustand'
    | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forms'
    | '/search'
    | '/posts/$postId'
    | '/themes/context'
    | '/themes/redux'
    | '/themes/zustand'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/forms'
    | '/posts'
    | '/search'
    | '/posts/$postId'
    | '/themes/context'
    | '/themes/redux'
    | '/themes/zustand'
    | '/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormsRoute: typeof FormsRoute
  PostsRoute: typeof PostsRouteWithChildren
  SearchRoute: typeof SearchRoute
  ThemesContextRoute: typeof ThemesContextRoute
  ThemesReduxRoute: typeof ThemesReduxRoute
  ThemesZustandRoute: typeof ThemesZustandRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRoute
    }
    '/themes/zustand': {
      id: '/themes/zustand'
      path: '/themes/zustand'
      fullPath: '/themes/zustand'
      preLoaderRoute: typeof ThemesZustandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes/redux': {
      id: '/themes/redux'
      path: '/themes/redux'
      fullPath: '/themes/redux'
      preLoaderRoute: typeof ThemesReduxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes/context': {
      id: '/themes/context'
      path: '/themes/context'
      fullPath: '/themes/context'
      preLoaderRoute: typeof ThemesContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
  }
}

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormsRoute: FormsRoute,
  PostsRoute: PostsRouteWithChildren,
  SearchRoute: SearchRoute,
  ThemesContextRoute: ThemesContextRoute,
  ThemesReduxRoute: ThemesReduxRoute,
  ThemesZustandRoute: ThemesZustandRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
